* Quick intro
=i3= is a great Window Manager. I am still learning it. The below notes reflect my knowledge around using the =i3= for doing common operations (even non-i3 related operations which typically have menus in other desktop managers). I will improve this document as I learn more efficient ways to do stuff.

* Steps to setup i3 window manager
I had installed Ubuntu intially then switched to i3. I had to carry out following steps,

 - Edit =.xsessionrc= file and put in the following
#+BEGIN_SRC 
# To start my chat client
pidgin &
# Since I am left handed (flip the mouse buttons)
xmodmap -e "pointer = 3 2 1"
# Similarly, change the touchpad to translate "tap" to clicking primary mouse button
synclient TapButton1=3
# Network manager applet
nm-applet &
#+END_SRC
 - My laptop is attached to external monitor. I need to switch between following settings,
   - Only laptop monitor (when it is not connected to external monitor)
   - Only external monitor (when I want to close laptop lid and only work on external monitor)
   - Both monitors (not cloned)
 - To achieve the above follow below steps,
   - Install arandr command with =sudo apt-get install arandr=
   - Launch =arandr= and configure above settings (primary monitor, resolution)
   - Save the settings as sh file (e.g. internal_monitor.sh, external_monitor.sh, both_monitors.sh etc.)
 - Now you can run the above created files to switch between various monitor layouts.
 - Press Mod1+Shift+r to make the pidgin and network manager appear in the tray.

* Quick commands
Convention: =C=: Ctrl, =S=: Shift, =M=: Mod1, =NUM=: Number, =DIR=: Direction, =RET=: Carriage Return/Enter, =SPC=: Space
 - Navigation
   - =M-NUM=: Go to workspace
   - =M-DIR=: Focus window in direction (can use =j/k/l/;= or arrow keys for direction)
   - =M-a=: Focus parent container (to do operations on siblings in the tree)
 - Split mode
   - =M-v=: Set vertical split for current container
   - =M-h=: Set horizontal split for current container
   - =M-w=: Tabbed layout for current container (horizontal)
   - =M-s=: Stack layout (vertical)
   - =M-e=: Default layout (tiled)
 - Run commands
   - =M-RET=: Open new terminal window
   - =M-d COMMAND=: Run COMMAND (suggestions are listed in the bar and you can choose using LEFT/RIGHT keys)
 - Moving windows
   - =M-S-NUM=: Send currently focused window to workspace NUM
   - =M-S-DIR=: Send window to given direction (may implicitly create new container dpending on resulting tree structure)
   - =M-S-q=: Kill window
 - Tiling/Floating
   - =M-f=: Toggle fullscreen
   - =M-SPC=: Switch to first tiled/floating container if current container is floating/tiled.
   - =M-S-SPC=: Toggle current container between floating/tiled.

* Configuration
** Setting new shortcuts
You can insert the following block in ~/.config/i3/config file towards the end to quickly launch new applications

You can press =M-o= to activate the new shortcuts (c, v, e) to launch respective applications and exit the mode with Esc.
#+BEGIN_SRC
set $mode_launch Launch: [c]hromium-browser, e[v]olution, [e]macs, Esc/Return: default mode
mode "$mode_launch" {
     bindsym c exec chromium-browser
     bindsym v exec evolution
     bindsym e exec emacs
     # back to normal: Enter or Escape
     bindsym Return mode "default"
     bindsym Escape mode "default"
}

bindsym $mod+o mode "$mode_launch"

#+END_SRC


* Common issues and solutions
** Not able to switch to other window when connected to citrix
 - For citrix fullscreen issue, press Ctrl-F2 followed by Mod1+<workspace number> to switch to other workspace
 - Use Mod1+Shift+NUMBER to switch the Citrix to its own workspace
** Unable to switch from remmina fullscreen (RDP client)
 - Press Right Ctrl-F
** Avoid laptop from suspending when lid closed
 - Edit =/etc/systemd/logind.conf=
   - Uncomment "HandleLidSwitch=suspend" param and change =suspend= to =ignore=
   - Restart login service with
     - =systemctl list-units | grep login=
     - =systemctl restart UNITNAME=
** Suspending laptop
You can run command =lock && systemctl suspend=
** Changing monitor brightness
You can do it through =xbacklight=
 - =xbacklight -inc 10=
 - =xbacklight -dec 10=



